# Generated by Django 5.1.4 on 2024-12-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_teacher_user_teacher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='content',
        ),
        migrations.AddField(
            model_name='notice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notices/', verbose_name='Attachment (PDF/Image)'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Notice Title'),
        ),
    ]
