# Generated by Django 5.1.4 on 2024-12-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_notice_content_notice_description_notice_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('student_class', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='blood_group',
            field=models.CharField(default='N/A', max_length=5),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='education_qualification',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='father_name',
            field=models.CharField(default='Unkown', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(default='Other', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gmail',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='teacher',
            name='mobile',
            field=models.CharField(default='01000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='teacher',
            name='mother_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='religion',
            field=models.CharField(default='Islam', max_length=50),
        ),
    ]
