# Generated by Django 5.1.4 on 2025-01-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_student_teacher_blood_group_teacher_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default='গ্রাম, উপজেলা, জেলা', verbose_name='ঠিকানা'),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(default='N/A', max_length=5, verbose_name='রক্তের গ্রুপ'),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01', verbose_name='জন্ম তারিখ'),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(default='ইসলাম', max_length=50, verbose_name='ধর্ম'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.TextField(default='Not provided'),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='অজানা', max_length=100, verbose_name='পিতার নাম'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(default='০১৭XXXXXXXX', max_length=15, verbose_name='মোবাইল নম্বর'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_name',
            field=models.CharField(default='অজানা', max_length=100, verbose_name='মাতার নাম'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='অজানা', max_length=100, verbose_name='নাম'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(choices=[('প্লে', 'প্লে'), ('নার্সারি', 'নার্সারি'), ('প্রথম', 'প্রথম'), ('দ্বিতীয়', 'দ্বিতীয়'), ('তৃতীয়', 'তৃতীয়'), ('চতুর্থ', 'চতুর্থ'), ('পঞ্চম', 'পঞ্চম'), ('ষষ্ঠ', 'ষষ্ঠ'), ('সপ্তম', 'সপ্তম'), ('অষ্টম', 'অষ্টম'), ('নবম', 'নবম'), ('দশম', 'দশম')], default='প্লে', max_length=50, verbose_name='শ্রেণি'),
        ),
    ]
