# Generated by Django 5.1.4 on 2025-01-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_student_address_student_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='designation',
            field=models.CharField(default='Teacher', max_length=100),
        ),
    ]
