# Generated by Django 5.1.4 on 2025-01-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_teacher_subject_teacher_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='hobby',
            field=models.CharField(default='Not specified', max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.TextField(default='পাবনা'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(default='1985-01-01'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mobile',
            field=models.CharField(default='01xxxxxxxxx', max_length=15),
        ),
    ]
