# Generated by Django 5.1.4 on 2025-01-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_teacher_hobby_alter_teacher_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(choices=[('ক', 'ক'), ('খ', 'খ'), ('গ', 'গ'), ('বিজ্ঞান', 'বিজ্ঞান'), ('বানিজ্য', 'বিনিজ্য'), ('মানবিক', 'মানবিক')], default='A', max_length=50, verbose_name='শাখা'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(default='N/A', verbose_name='ঠিকানা'),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(default='N/A', max_length=50, verbose_name='ধর্ম'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
