# Generated by Django 5.1.4 on 2025-01-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_student_section_alter_student_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.PositiveIntegerField(default=1, verbose_name='রোল নম্বর'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(default='N/A', max_length=15, verbose_name='মোবাইল নম্বর'),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(choices=[('ক', 'ক'), ('খ', 'খ'), ('গ', 'গ'), ('বিজ্ঞান', 'বিজ্ঞান'), ('বানিজ্য', 'বিনিজ্য'), ('মানবিক', 'মানবিক')], default='N/A', max_length=50, verbose_name='শাখা'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(choices=[('প্লে', 'প্লে'), ('নার্সারি', 'নার্সারি'), ('প্রথম', 'প্রথম'), ('দ্বিতীয়', 'দ্বিতীয়'), ('তৃতীয়', 'তৃতীয়'), ('চতুর্থ', 'চতুর্থ'), ('পঞ্চম', 'পঞ্চম'), ('ষষ্ঠ', 'ষষ্ঠ'), ('সপ্তম', 'সপ্তম'), ('অষ্টম', 'অষ্টম'), ('নবম', 'নবম'), ('দশম', 'দশম')], default='N/A', max_length=50, verbose_name='শ্রেণি'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('student_class', 'section', 'roll_number')},
        ),
    ]
