# Generated by Django 5.1.4 on 2025-01-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_student_roll_number_alter_student_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.PositiveIntegerField(verbose_name='রোল নম্বর'),
        ),
    ]
