# Generated by Django 5.1.4 on 2025-01-18 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_student_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.PositiveIntegerField(default=1, verbose_name='রোল নম্বর'),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(choices=[('ক', 'ক'), ('খ', 'খ'), ('গ', 'গ'), ('বিজ্ঞান', 'বিজ্ঞান'), ('বিনিজ্য', 'বিনিজ্য'), ('মানবিক', 'মানবিক')], default='N/A', max_length=50, verbose_name='শাখা'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='তারিখ')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10, verbose_name='স্থিতি')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student', verbose_name='শিক্ষার্থী')),
            ],
        ),
    ]
