# Generated by Django 5.1.4 on 2025-01-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_student_roll_number_alter_student_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.PositiveIntegerField(verbose_name='রোল নম্বর'),
        ),
    ]
