# Generated by Django 5.1.4 on 2025-01-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_student_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(choices=[('ক', 'ক'), ('খ', 'খ'), ('গ', 'গ'), ('বিজ্ঞান', 'বিজ্ঞান'), ('বানিজ্য', 'বানিজ্য'), ('মানবিক', 'মানবিক'), ('None', 'No Section')], default='None', max_length=50, verbose_name='শাখা'),
        ),
    ]
